### ISSUE TITLE
Upload constructor thows an exception nested by NullPointerException

### ISSUE THREAD

**Issue by ray-mints** [vaadin/vaadin-upload#351]
I use Vaadin 10.
So I have a MainUI class that extends SplitLayout. Inside I have object of WorkLayout  (WorkLayout extends VerticalLayout). WorkLayout has few buttons in a constructor and an Upload.
If I write `@SpringComponent` at the top of my MainUI - my spring boot project won't start, unless I delete Upload or put it in try catch. (If I put it in a try catch - it won't create Upload component on the screen at all and will just do whatever is in catch).
After trying to change things in my code - I figured that the `Upload upload = new Upload();` is causing it.
(If i change to `Upload upload = new Upload(buffer);` - the problem is the same. In fact, even a single line with `new Upload();` cause the error.)
Here is the error:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-06-11 14:20:22.219 ERROR 7985 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mainUI' defined in file [/home/username/work/myproject/target/classes/com/example/myproject/frontend/main/MainUI.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.myproject.frontend.main.MainUI]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1236)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.example.myproject.MyProjectApplication.main(MyProjectApplication.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.example.myproject.frontend.main.MainUI]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1228)
	... 22 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.vaadin.flow.server.communication.StreamRequestHandler.generateURI(StreamRequestHandler.java:135)
	at com.vaadin.flow.server.StreamResourceRegistry.getURI(StreamResourceRegistry.java:131)
	at com.vaadin.flow.server.StreamResourceRegistry.getURI(StreamResourceRegistry.java:126)
	at com.vaadin.flow.internal.nodefeature.ElementAttributeMap.setResource(ElementAttributeMap.java:124)
	at com.vaadin.flow.dom.impl.BasicElementStateProvider.setAttribute(BasicElementStateProvider.java:316)
	at com.vaadin.flow.dom.Element.setAttribute(Element.java:342)
	at com.vaadin.flow.component.upload.Upload.<init>(Upload.java:75)
	at com.example.myproject.frontend.main.sublayouts.WorkLayout.<init>(WorkLayout.java:51)
	at com.example.myproject.frontend.main.MainUI.<init>(MainUI.java:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
	... 24 common frames omitted

```

**Comment by tomivirkki** [comment]
Closing. Seems to work on V14.4

**Comment by chkpnt** [comment]
I just had the same issue. When you annotate a component just with `@SpringComponent` (without a scope), it's a singleton and will be preinitialized by Spring. You need to ensure that `Upload` is only used by beans with at least `@UIScope` to prevent the NPE caused by `UI.getCurrent()`.

According to the [documentation](https://vaadin.com/docs/latest/flow/integrations/spring/scopes), `@Route` should imply a prototype scope.

> All Flow routing components (@Route, RouterLayout or HasErrorParameter) are initialized by Spring, even without explicitly adding the @SpringComponent annotation. Without any annotations, the components act like a bean in prototype scope.

But in my experience, this isn't true (don't know if this is a bug in the documentation or the implementation): You need an explicit `@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)` if you really want a prototype.

**Comment by web-padawan** [comment]
@chkpnt Could you please submit a new issue?

**Comment by chkpnt** [comment]
Mh, I don't think there is a bug with `vaadin-upload`. I just wanted to add the hint for other developers stumbling over this issue, that a `@SpringComponent` might need a `@UIScope` or something else like in this case.
