### ISSUE TITLE
Vaadin upload cause "Unexpected Server Error" for PNG images files.

### ISSUE THREAD

**Issue by JKostikiadis** [vaadin/vaadin-upload#371]
### Description
Code from https://vaadin.com/components/vaadin-upload/java-examples to upload image files cause an exception for png files ( jpeg files works fine ). 

Add the code to any view on your app

```
MemoryBuffer buffer = new MemoryBuffer();
Upload upload = new Upload(buffer);
upload.setAcceptedFileTypes("image/jpeg", "image/png");
upload.setMaxFileSize(MAX_SIZE); 
Div output = new Div();

upload.addSucceededListener(event -> {
	try {
		byte[] bytes = IOUtils.toByteArray(buffer.getInputStream());
		// do something
	} catch (IOException e) {
		e.printStackTrace();
	}
});

upload.addFileRejectedListener(event -> {
	Paragraph component = new Paragraph();
	showOutput(event.getErrorMessage(), component, output);
});

add(upload, output);
```

```
private void showOutput(String text, Component content, HasComponents outputContainer) {
	HtmlComponent p = new HtmlComponent(Tag.P);
	p.getElement().setText(text);
	outputContainer.add(p);
	outputContainer.add(content);
}
```

### Steps to reproduce
1. Clean project from https://start.vaadin.com/
2. Vaadin 18 Java project
3.  Using the code above try to load any png image

### Expected outcome
Like jpeg files I would expect to succeed on file loading or either get a better error message. 

### Actual outcome
stack trace error : 

```
org.apache.tomcat.util.http.fileupload.impl.FileSizeLimitExceededException: The field file exceeds its maximum permitted size of 1048576 bytes.
	at org.apache.tomcat.util.http.fileupload.impl.FileItemStreamImpl$1.raiseError(FileItemStreamImpl.java:114) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.util.http.fileupload.util.LimitedInputStream.checkLimit(LimitedInputStream.java:76) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.util.http.fileupload.util.LimitedInputStream.read(LimitedInputStream.java:135) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at java.io.FilterInputStream.read(Unknown Source) ~[na:1.8.0_261]
	at org.apache.tomcat.util.http.fileupload.util.Streams.copy(Streams.java:98) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:291) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.connector.Request.parseParts(Request.java:2869) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.connector.Request.getParts(Request.java:2771) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.connector.RequestFacade.getParts(RequestFacade.java:1098) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:95) ~[spring-web-5.3.1.jar:5.3.1]
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.<init>(StandardMultipartHttpServletRequest.java:88) ~[spring-web-5.3.1.jar:5.3.1]
	at org.springframework.web.multipart.support.StandardServletMultipartResolver.resolveMultipart(StandardServletMultipartResolver.java:87) ~[spring-web-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.DispatcherServlet.checkMultipart(DispatcherServlet.java:1199) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1033) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) ~[tomcat-embed-core-9.0.39.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.39.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.1.jar:5.3.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.1.jar:5.3.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.1.jar:5.3.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.1.jar:5.3.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.1.jar:5.3.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.1.jar:5.3.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_261]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.39.jar:9.0.39]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_261]
```

Error on client :

![image](https://user-images.githubusercontent.com/26612500/102723740-f98a6100-4312-11eb-88d6-74f3e0d4382b.png)

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Opera

**Comment by DiegoCardoso** [comment]
Hi @JKostikiadis

Just by looking at the stack trace, it seems that the issue is not with the file type, but rather that you are trying to upload a file larger than the limit:
```
The field file exceeds its maximum permitted size of 1048576 bytes.
```

Could you try with a smaller PNG image?

**Comment by JKostikiadis** [comment]
Hi @DiegoCardoso 
I forgot to say that in the line below the variable MAX_SIZE = 20971520; // max 20MB
`upload.setMaxFileSize(MAX_SIZE); `
After further testing I saw that the stack trace is wrong for PNG and JPEG alike. The stack trace keep saying that the max size is 1048576 bytes. Even if I tried to put there a huge value just to make any kind of png/jpeg to be acceptable it still complaining about the size. 
If I reduce the MAX_SIZE variable to a really small value then for both png and jpeg instead of just getting a huge stack trace, I get this : 

![image](https://user-images.githubusercontent.com/26612500/102987767-86a00680-451b-11eb-83a1-ce2dc1377f7d.png)

Which is actually what I would expect in the first place. So the conclusion is that the method `setMaxFileSize` is working partially if I only reduce the size but I can't increase it for some ready. 

I hope I didn't forget to mention anything

**Comment by tomivirkki** [comment]
I wonder if the issue is related to [this config](https://stackoverflow.com/a/39534619)...have you set a non-default value for it in your project?

**Comment by JKostikiadis** [comment]
You right! I just add those two values to the application.properties file and now everything works fine!!.

```
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
```

So I guess I guess those values must be added every time a new project is created ( if it has something to do with upload ) 
Because I didn't change any default value in any config file. As I said even if I had a clean project from the vaadin.start I still couldn't make it work with big files. I thought the `setMaxFileSize()` method will handle everything.

In any case, thanks for your time. 
I will leave the "closing" of this issue to you, because I am still not sure if this is a bug with setMaxFileSize method or not.

**Comment by tulioag** [comment]
The defaults seem to be coming from [MultipartProperties](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/servlet/MultipartProperties.html)

They are 1 MB per file and 10MB total request size. If a file is larger then the maximum, an exception is thrown in [LimitedInputStream (tomcat)](https://tomcat.apache.org/tomcat-9.0-doc/api/index.html?org/apache/tomcat/util/http/fileupload/util/LimitedInputStream.html). I don't think that exception can be caught by the component.

I also don't think it is appropriate for `Upload.setMaxFileSize` to change those values, because

- They are global
- They are specific to Spring Boot

This behaviour is unclear, but I can not think of a good way to solve this.
